package com.example.zenithco.ui.theme

import androidx.compose.ui.graphics.Color

// -- Luxury Tones for Zenith & Co (Light Mode) --
val primaryLight = Color(0xFF0D131C)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF222831)
val onPrimaryContainerLight = Color(0xFF898F9A)
val secondaryLight = Color(0xFF5D5E63)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDFDFE4)
val onSecondaryContainerLight = Color(0xFF616267)
val tertiaryLight = Color(0xFF5D5F5F)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFEEEEEE)
val onTertiaryContainerLight = Color(0xFF6A6C6C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCF8F9)
val onBackgroundLight = Color(0xFF1C1B1C)
val surfaceLight = Color(0xFFFCF8F9)
val onSurfaceLight = Color(0xFF1C1B1C)
val surfaceVariantLight = Color(0xFFE2E2E7)
val onSurfaceVariantLight = Color(0xFF45474B)
val outlineLight = Color(0xFF75777C)

// -- Luxury Tones for Zenith & Co (Dark Mode) --
val primaryDark = Color(0xFFC1C7D3)
val onPrimaryDark = Color(0xFF2B313A)
val primaryContainerDark = Color(0xFF222831)
val onPrimaryContainerDark = Color(0xFF898F9A)
val secondaryDark = Color(0xFFC5C6CB)
val onSecondaryDark = Color(0xFF2E3034)
val secondaryContainerDark = Color(0xFF47494D)
val onSecondaryContainerDark = Color(0xFFB7B8BD)
val tertiaryDark = Color(0xFFFFFFFF)
val onTertiaryDark = Color(0xFF2F3131)
val tertiaryContainerDark = Color(0xFFE2E2E2)
val onTertiaryContainerDark = Color(0xFF636565)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131314)
val onBackgroundDark = Color(0xFFE5E2E2)
val surfaceDark = Color(0xFF131314)
val onSurfaceDark = Color(0xFFE5E2E2)
val surfaceVariantDark = Color(0xFF45474B)
val onSurfaceVariantDark = Color(0xFFC5C6CB)
val outlineDark = Color(0xFF8F9095)
